global using System;
global using System.Collections.Generic;
global using System.Linq;
global using FluentAssertions;
global using FsCheck;
global using FsCheck.Xunit;
global using Spectre.Console;
global using Spectre.Console.Testing;
global using Xunit;
